language: node_js

node_js:
  - '4'

env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=master

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

cache:
  apt: true
  directories:
  - node_modules

script:
  - gulp prod

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: ds-mm-partner
  skip_cleanup: true
  region: us-east-1
  local_dir: _site
  acl: public_read
  on:
    repo: MissingMaps/partners
    branch: "${DEPLOY_BRANCH}"
