language: node_js

node_js:
  - '0.12'

script:
  - gulp prod

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: ds-mm-partner
  skip_cleanup: true
  region: us-east-1
  local_dir: _site
  acl: public_read
  on:
    repo: MissingMaps/partners
    branch: develop
