language: node_js

node_js:
  - '0.12'

script:
  - gulp prod

deploy:
  provider: s3
  access_key_id:
    secure: "aaj/tqmjVbCVVOl6nGyAMWzY55BrktyXRqfhFHZpLOET/5noyT0VNpy/wXTCUM+Hg4VcO7cmxO4hje4hgdkx6mZl3hIHMcGFTmwDfKFbjwwtitpep2KI0AsQ6dtex5eXIR0enzU7F5+cVlEaxr2vBYj3whXehtjGXnG0++68OQdzHB4Gp4cEFuRsh/JlL5KcJD/omg/NHSY4b7jpwu0sN+WFYSrdYwjphksFxkbrlBH+hS9jnTyOanjfl222kc8StmN2acEgaGX2i4UUe8W86fq0iy+WiR514kcxlwKaiFow5HZ1Q21yCN2z1rc2rDNMFB1I3B0MnOQkBYfxViD6/EDZObnzoLjdhLXvB6M8gQPPNOx32Dzqr81vBKDQ01trEi8fGhLfh6Hdr/vUOADzHb7A8c3xj/Z+A26Ao6fxxmeX9i85mO7rEJNCkIzMvpB+0tfZMLBeko6d6tFnSFYdn65HdDVfzF5IZgbxXN2MSQpdtqjyytJYsWJikzeJKsgRZIJdQpA7clht7vBqQLhJyvGsdzAi11BWymLiCSIekMMTydy85NBlOWKrh48ZRGzv9xi3XX9Ip0t3S0toWkV+jPoWdXYTa+uM5E4jVhZkPIU3Q3x4Q3H+Yn1n56mt8nV0MuRVmksTKbRoouqlaIhC+TPEf75qgW5W8N/ZBXBghzY="
  secret_access_key:
    secure: "TTP3nTCfKG4k7HLvjbwS+kErI2bsnCLtDT/UoCOXDzR3bWroZuO89W0GbZci4Ja07VAB5KdvimLIZCaFXZyRoQEPoe9SNDoUwPDGxkhWF9mhJwFy15BfblSy9GnnWq8Ames52OlMZQyfxq0pJLk1HxpK2Vkvfx806OZxZyIyKW+TsWIBcfcnLIw9/UryQcVO8CnJNHOc/AkpzINz7CoHrH2GhgkwZlEP4/vmiSKdQv8TXp4Zqf+CZFYDyIY/hjR/VC9/R2MDcTx0nQn7kXgZy1jBOQhSCcStYALNgrNtrGxFTmkjuT11Jgg9SPnvnAdqMeDPbBIv1rbcOZ075Yb/2xjxqQqhE7AlK3oud33NJyPJqXIlMYQwUnfNxgYokVIj1t9SSoGAbMhRyW7pfY+g21e3LFKtoCOyhLbbEHHl6/ZZnJWqv5SC7Tiwu7fjsMsp+OFwZAdMkD/bbWetCe53SJ+2jzQi2zTqYPv0v1uYHjGzK3pXb6VyYhN7wb/MDLBfL9cXLEJ00yOVMPKaESVdqymgiJ/4bD+/E0t6NJRzYzIu4AZi0r3yVHzSUv6wsKXqFrYUpx4/AgovNRhcAJFAqHcH4T1ECCSAOTcEKmRusqX251VJEyPVfaBUQm8+/G+eMURqzpHMoLA0KTOiEk/eYHwsbR8FzmD54FhAYcSa7G8="
  bucket: ds-mm-partner
  skip_cleanup: true
  region: us-east-1
  local-dir: _site
  acl: public_read
  on:
    repo: developmentseed/mm-partner-page
    branch: develop
