language: node_js

node_js:
  - '0.12'

script:
  - gulp prod

deploy:
  provider: s3
  access_key_id: AKIAIVZKYLI3JZ4M53AA
  secret_access_key:
    secure: "GE+ftZb2haBdRQmgVknhxodujFqEiB32Bks1gecNXb6AZVbppC2Za1u8vAHZBjO9I/euJuLXPrhyoYBVO/YrhwktP2tnmfY/pDy6igecA9EulhhEG0jKL4gUiGy2qWXd48gWBOGYKxIkiVHZFF5bXllKky6YA/eKu5hp74FgtNEWj3GVj1B5KfOwxz/pZk0Jm23pTUFJrs3OaH/blJVCVsEfIQ0TyqOOuCJrWxMhQUl47R0HNHeijMl2fa7hCyxN/wTkiYfftydobwbCGcmnu8MQuYCtOci7k2cwMF1OBF73MH/K1Z+B3bKmA8hXr0R/2oUX+s8H5xLeJiz/eQ2jfh30Cg6Jh1j3nk6n1/fmgGIri21v6zau3U2NTPCZuuXuUq/LmmRMremAnfSmakNhJGcEqLywAnPqomjgUnySB8/3KcY2eZI+xFcNyR8//FqCBAg4WIBL+n0ecAMngiBNj+S/1kN9RpiZ4YiWzNRmgt4wgsqisi5l+ha0oRRjmrK5nk7eVbOwwFzZR/a5aeHXaBK6JOUZbm+iKfcby1ziYuHNSGPJYUy9hHbm4TcrjXFYB5+Id4etYGmqwlgfPNO78eQ2IrHJk+1XhMEgyHvnDuEZtaQbkhh1tSQKBTRV8ekM1g6pivd5Cbvmbjo16nH31bPiJKv8Sgc/lf0mMedBzv4="
  bucket: ds-mm-partner
  skip_cleanup: true
  region: us-east-1
  local-dir: _site
  acl: public_read
  on:
    repo: developmentseed/mm-partner-page
    branch: develop
