language: node_js

node_js:
  - '0.12'

script:
  - gulp prod

deploy:
  provider: s3
  access_key_id:
    secure: "mPsr1kBgWrsCrXDlOmIATtsMtO8p5WBlN6/fAZJDnDZsTMIyRF6utfWT+7BcybSCFg300pjtgbCzSP0J2jnpAj+kILsuQcRugpv36vP4ZQ9CvTI/YRIY9ijSYGMvX9DNm+Onn/4gX1vs7Xk+PFVq68CND8q7WjxTGwUEEiYkX4ebAVYvcx/WyHES+jwyn6krJ1YKaP4cY23shIXJsYElGYmhQr4ijSMK5g0D964DUAVaDK0qwGVepI+RzokW5UY3YmUP+k4kr9r07yKywtZtodmClny/3ekLQ5dQItGryTq8y7fBpg0FnGsHy8G5onQe0VvKbY+Q2xYg4bjDa0Ii0c96s8QQjE15bs1a8YUx9abNN7+d+76rD4+SlOIW6q0cEvy1ssWBcc7mG4SdBjlxZhBZbSWef76MuEGhcf9gkMz4stoEXhnaFZnyjnE6ZF18rw7XPeBxdSwfnQ4Ip3riczS2xuISDrMDhCvjV2LIO2SCY1GYvwgW0MJX7ZMV8pnOlHmbNMrm5oQOwu37eJcSO5QRi1MEpJweoP0jnRIkh4my5qcMzm1elU0VUsVcGFPBZAj9vcMh7ND0QP9lAxVCA7NSpw49duhUo5YmEEO1cr+PEAdtwD6K+pEDqZ8UxHUu0uzADoYVBLtzg3jJMOL2okLpobZAI1adu1GCiRFGL8w="
  secret_access_key:
    secure: "TjaQQEkZKmfXzzliDo79gc2SjUS/n37qW68B9H/sgYGrhqJ8vIAyBKGp93jD+Q47GsRZHsa7+tjbjpiiKoiVryKGebu+9bu87CNZ85R5lnhs0j4ICoJxJ3v2EglaI1bTRAOGKzuKYC/nXdY00X1rNX7jrmBSAXrAEFS7GxM8jLVzddY+ABiEJRh+/gja2cQjGaB67Vdv7GK+gXjzy1V+5yRiap80BR81LS77TZlRs4y6WhpNh6HF5oXylakJl4CSIVLEfS79QhqMGkfa5MdT39hdvD7thFHxC7E4d3qZG7BtCyz9jAr1GRLpSqP1l8X9Ast3JvwwusQmUxOldQ40VUw7YWJC06iGVrT7KV+PQq0t6eBMjxxC2L6pMqJZMyYvlYiBB0Exfab1jCnHCiU/ryTC56Yct8x0Em7aoz01eDS1Ps4ns0sZi0IHGTZ+ECpObZadFwAyub1yxHaLnvWTS4XalsyRkzltoAXP0nX1EXg9jG24xYlbMA8aaVZg/sqWbbOHL7/0Cv+gTJ3A8VZp7ghDNdbOCTKCSDjFT/ouLZK7jJKgynmzQFHcmN82uUrpz2IZQWP2niO++o1xU6f5rY5Rk9dVUcu/8Eg/5B9/qTPS33MGizA1siUc0pm7lwvtYThIi02ZAj6g8eL7AsJAAmqUqDnnYFzOz2b+H+8aCrQ="
  bucket: ds-mm-partner
  skip_cleanup: true
  region: us-east-1
  local-dir: _site
  acl: public_read
  on:
    repo: developmentseed/mm-partner-page
    branch: develop
