# Site settings
title: missingmaps
safe:           false
source:         app
exclude:
  - assets/scripts
  - assets/vendor
  - assets/styles
  - README.md
timezone: America/New_York
highlighter: false 

baseurl: ".."

collections:
  subhashtags:
    output: true

  tm-projects:
    output: true