# Site settings
title: Apple Missing Maps
safe:           false
source:         app
exclude:
  - assets/scripts
  - assets/vendor
  - assets/styles
  - README.md
timezone: America/New_York
highlighter: false

domain:         http://missingmaps.apple.com
path_prefix:    /

default_partner: apple

collections:
  partner:
    output: true
    permalink: /:path/
    lang: en

# locale settings
default_locale:     "en"
authorized_locales: ["en"]
